export const PATH = {
  LOGIN: '/login',
  SIGNUP: '/signup',
  ONBOARDING: '/',
  HOME: '/home',
  MYPAGE: '/mypage',
  MY_ACHIEVEMENT: '/mypage/achievement',
  MY_LIFE_LIST: '/mypage/my-life-list',
  MY_GONGGAM_POST_LIST: '/mypage/my-gonggam-post-list',
  GONGGAM: '/gonggam',
  GONGGAM_DAILY: '/gonggam/daily',
  GONGGAM_POST: '/gonggam/post',
  LIFE: '/life',
  LIFE_POST: '/life/post',
  CHECKLIST: '/checklist',
  MEAL_CHECKLIST: '/checklist/혼밥',
  TRAVEL_CHECKLIST: '/checklist/혼자여행',
  GOD_LIFE_CHECKLIST: '/checklist/갓생',
  PLAY_CHECKLIST: '/checklist/혼놀',
  CLEAN_CHECKLIST: '/checklist/청소',
  CHECKLIST_POST: '/checklist/post',
  ERROR: '/error'
};
