export const PATH = {
  LOGIN: '/login',
  SIGNUP: '/signup',
  HOME: '/',
  MYPAGE: '/mypage',
  MY_ACHIEVEMENT: '/mypage/achievement',
  MY_LIFE_LIST: '/mypage/my-life-list',
  MY_GONGGAM_POST_LIST: '/mypage/my-gonggam-post-list',
  GONGGAM: '/gonggam',
  GONGGAM_DAILY: '/gonggam/daily',
  LIFE: '/life',
  LIFE_POST: '/life/post',
  CHECKLIST: '/checklist',
  MEAL_CHECKLIST: '/checklist/혼밥',
  TRAVEL_CHECKLIST: '/checklist/혼자여행',
  GOD_LIFE_CHECKLIST: '/checklist/갓생',
  PLAY_CHECKLIST: '/checklist/혼놀',
  CLEAN_CHECKLIST: '/checklist/청소',
  CHECKLIST_POST: '/checklist/post',
  ERROR: '/error',

  MEAL: '/checklist/%ED%98%BC%EB%B0%A5',
  TRAVEL: '/checklist/%ED%98%BC%EC%9E%90%EC%97%AC%ED%96%89',
  GOD_LIFE: '/checklist/%EA%B0%93%EC%83%9D',
  PLAY: '/checklist/%ED%98%BC%EB%86%80',
  CLEAN: '/checklist/%EC%B2%AD%EC%86%8C'
};
